name: Build and release agent

on:
  push:
    branches:
      - setup-build
#    tags:
#      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm i --prefix agent
          npm run build --prefix agent
      - name: Read package.json
        id: package
        uses: myrotvorets/info-from-package-json-action@0.0.2
        with:
          path: ./agent
      - name: Create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - name: Upload Windows build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./agent/exe/${{ steps.package.outputs.packageName }}-${{ steps.package.outputs.packageVersion }}-windows.exe
          asset_name: ${{ steps.package.outputs.packageName }}-${{ steps.package.outputs.packageVersion }}-windows.exe
          asset_content_type: application/vnd.microsoft.portable-executable
